image: node:latest

stages:
  - build
  - test
  - production
  
process compile:
  stage: build
  script: 
    - npm install

process test:
  stage: test
  script:
    - npm test

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=basic-commerce --api-key=$HEROKU_API_KEY
  only:
    - master
